Secretaria/Secretaria.View/Controllers/AlunoController.cs
using Microsoft.AspNetCore.Mvc;
using Secretaria.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Secretaria.View.Controllers
{
    public class AlunoController : Controller
    {
        Dbo_SecretariaContext odb;

        public AlunoController()
        {
            odb = new();
        }
        public IActionResult Index()
        {
            var oLista = odb.TbAluno.Include(d => d.CursoIdCursoNavigation).AsNoTracking();
            
            return View(oLista);
        }
        public IActionResult Create()
        {
            var lista = new SelectList(odb.TbCurso.ToList(), "IdCurso" , "NomeCurso");
            ViewBag.ListaCurso = lista;
            return View();
        }
        public IActionResult Delete(int id)
        {
            TbAluno oAluno = odb.TbAluno.Find(id);
            return View(oAluno);
        }
        public IActionResult Edit(int id)
        {
            var lista = new SelectList(odb.TbCurso.ToList(), "IdCurso", "NomeCurso");
            ViewBag.ListaCurso = lista;
            TbAluno oAluno = odb.TbAluno.Find(id);
            return View(oAluno);
        }
        public IActionResult Details(int id)
        {
            var lista = new SelectList(odb.TbCurso.ToList(), "IdCurso", "NomeCurso");
            ViewBag.ListaCurso = lista;
            TbAluno oAluno = odb.TbAluno.Find(id);
            return View(oAluno);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int id, TbAluno oAluno)
        {
            
            TbAluno oaluno = odb.TbAluno.Find(id);
            return View(oaluno);

        }
            [HttpPost]
            [ValidateAntiForgeryToken]
        public ActionResult Delete(TbAluno oAluno)
        {
            odb.Remove(oAluno);
            odb.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TbAluno oAluno)
        {
            var oAlunoBanco = odb.TbAluno.Find(id);
            oAlunoBanco.Nome= oAluno.Nome;
            oAlunoBanco.Cpf=oAluno.Cpf;
            oAlunoBanco.DataInicio= oAluno.DataInicio;
            odb.Entry(oAlunoBanco).State = EntityState.Modified;
            odb.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TbAluno oAluno)
        {
            
            odb.TbAluno.Add(oAluno);
            odb.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Secretaria/Secretaria.View/Controllers/CursoController.cs
using Microsoft.AspNetCore.Mvc;
using Secretaria.Model;
using Microsoft.EntityFrameworkCore;

namespace Secretaria.View.Controllers
{
    public class CursoController : Controller
    {
        Dbo_SecretariaContext odb;

        public CursoController()
        {
            odb = new();
        }
        public IActionResult Index()
        {
            List<TbCurso> oLista = odb.TbCurso.ToList();
            return View(oLista);
        }
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Delete(int id)
        {
            TbCurso oCurso = odb.TbCurso.Find(id);
            return View(oCurso);
        }
        public IActionResult Edit(int id)
        {
            TbCurso oCurso = odb.TbCurso.Find(id);
            return View(oCurso);
        }
        public IActionResult Details(int id)
        {
            TbCurso oCurso = odb.TbCurso.Find(id);
            return View(oCurso);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int id,TbCurso oCurso)
        {
            TbCurso ocurso = odb.TbCurso.Find();
            return View(ocurso);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TbCurso oCurso)
        {
           
            odb.TbCurso.Add(oCurso);
            odb.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(TbCurso oCurso)
        {
            odb.Remove(oCurso);
            odb.SaveChanges();
            return RedirectToAction("Index");
        }

        public Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry<TbCurso> GetEntityEntry(TbCurso oCurso)
        {
            return odb.Entry(oCurso);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TbCurso oCurso)
        {
            var oCursoBanco = odb.TbCurso.Find(id);
            oCursoBanco.NomeCurso = oCurso.NomeCurso;   
            oCursoBanco.Descricao = oCurso.Descricao;
            odb.Entry(oCursoBanco).State = EntityState.Modified;
            odb.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Secretaria/Secretaria.View/Controllers/MatriculaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Secretaria.Model;
using Microsoft.EntityFrameworkCore;

namespace Secretaria.View.Controllers
{
    public class MatriculaController : Controller
    {
        Dbo_SecretariaContext odb;

        public MatriculaController()
        {
            odb = new();
           
        }       
        public IActionResult Index()
        {
            var List = odb.TbMatricula.Include(d => d.CursoIdCursoNavigation).Include(e => e.AlunoIdAlunoNavigation).AsNoTracking();
            return View(List);
    
        }

        public IActionResult Create()
        {
            var lista = new SelectList(odb.TbCurso.ToList(), "IdCurso", "NomeCurso");
            ViewBag.ListaCurso = lista;
            var lista2 = new SelectList(odb.TbAluno.ToList(), "IdAluno", "Nome");
            ViewBag.ListaAluno = lista2;
            return View();
        }
        public IActionResult Edit(int id)
        {
            var lista = new SelectList(odb.TbCurso.ToList(), "IdCurso", "NomeCurso");
            ViewBag.ListaCurso = lista;
            var lista2 = new SelectList(odb.TbAluno.ToList(), "IdAluno", "Nome");
            ViewBag.ListaAluno = lista2;
            TbMatricula oMatricula = odb.TbMatricula.Find(id);
            return View(oMatricula);
        }
        public IActionResult Delete(int id)
        {
            var lista = new SelectList(odb.TbCurso.ToList(), "IdCurso", "NomeCurso");
            ViewBag.ListaCurso = lista;
            var lista2 = new SelectList(odb.TbAluno.ToList(), "IdAluno", "Nome");
            ViewBag.ListaAluno = lista2;
            TbMatricula oMatricula = odb.TbMatricula.Find(id);
            return View(oMatricula);
        }
        public IActionResult Details(int id)
        {
            var lista = new SelectList(odb.TbCurso.ToList(), "IdCurso", "NomeCurso");
            ViewBag.ListaCurso = lista;
            var lista2 = new SelectList(odb.TbAluno.ToList(), "IdAluno", "Nome");
            ViewBag.ListaAluno = lista2;
            TbMatricula oMatricula = odb.TbMatricula.Find(id);
            return View(oMatricula);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int id, TbMatricula oMatricula)
        {
            TbMatricula omatricula = odb.TbMatricula.Find(id);
            return View(omatricula);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(TbMatricula oMatricula)
        {
            odb.Remove(oMatricula);
            odb.SaveChanges();
            return RedirectToAction("Index");

        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TbMatricula oMatricula)
        { 
            odb.TbMatricula.Add(oMatricula);
            odb.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TbMatricula oMatricula)
        {
            var oMatriculaBanco = odb.TbMatricula.Find(id);
            oMatriculaBanco.AlunoIdAluno = oMatricula.AlunoIdAluno;
            oMatriculaBanco.CursoIdCurso = oMatricula.CursoIdCurso;
            oMatriculaBanco.Situacao=oMatricula.Situacao;
            odb.Entry(oMatriculaBanco).State = EntityState.Modified;
            odb.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Secretaria/Secretaria.View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Secretaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Secretaria.View.styles.css" asp-append-version="true" />
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 navbar justify-content-center style="background-color: #20c997
;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Secretaria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav justify-content-center flex-grow-1">
                        <li class="nav-item ">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Curso"asp-action="Index">Curso</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Aluno" asp-action="Index">Aluno</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Matricula" asp-action="Index">Matrícula</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Secretaria.View 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>